apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:BvD41RrLFG7noEnc6gvwLQ==,iv:Ovwaq7SnTxkMmhOMb0MG3gRxdR48JQIl2MsPv2OlnEo=,tag:eWNP1benohhAxdOnzyO7iA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:p3Q1P8kswvrwaKbmhHnsFfd+jjq6c+fevMqolv3OHeuTxEPhxNZk9Q==,iv:sbvW1szPndXqcEdUxKWeuZfPSEnPLv3vaR/14kTjUiA=,tag:k0VJUfMEbJhaL8nCQMiJfA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1afcgy452mzg0qx5dlk70qsu7cnsqng0xxxsrzq0v8reyqyqpwgpqcltksm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU3lsb3B0MnFBdVV4L2w3
            cFN3T1dnU2hGWCtEc0RtWDlFYWNHQzlTaEVvCmJkY09xdlFTc05Pc3hTMU55Ui9z
            V3RGRG9vK1J1ZzJNb20raGRMVDdFTmsKLS0tIDAvV1pXR3I3UFJTeFVXUC9QMTRv
            cWluSkRJQThHZXpYQ094anBUTkI5QXcK3m3RHcdxU8J7vm9+5umAjd6RFXQ8LnzI
            KMpQNM7FCyir6Y6gFzmVe+G1jLiYPjy2UiJ+DfB9ISBPFxC8jPTxnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T03:08:52Z"
    mac: ENC[AES256_GCM,data:ULBtdq80MxGZC08xMBbIQknLM3+B0kFVspJIx/Ib27BT2P23TMdfoUtRLSI8m0k7FFI2VRBamDPj/8VNbZd4Wb8Gf9NseAHc56spyWZImWygKqXJ94h+aYNTc5T9kXzGfWr4ZZ++j3a/v21R09cNwGVeDLk1VFIVjUA/MUJd/xg=,iv:hJoEt+ZgGwDYqJ7p+8CLaQCWk1UYCFj6oFLtl/Xx8kk=,tag:cBuAIK+RNp8r6cWjPNf6Jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
