apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-immediate
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  path: "/var/lib/rancher/k3s/storage"
  nodePathMap: "k3s-remus=/var/lib/rancher/k3s/storage:k3s-romulus=/var/lib/rancher/k3s/storage"
  
